[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bookstack-api"
version = "0.1.0"
description = "BookStack API package"
authors = [
    {name = "Robin Niemann", email = "robin@rn-software-services.de"},
    {name = "Stina Niemann"},
]
